import Head from 'next/head'
import { Layout } from '../components/Layout'
import '../styles/globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import 'mdb-react-ui-kit/dist/css/mdb.min.css'
import { GlobalProvider } from '../context/contextGlobal'

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Segoro</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <GlobalProvider>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </GlobalProvider>
    </>
  )
}

export default MyApp
